# Generated by Django 5.1.1 on 2024-10-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("land", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="parent_land",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="land.land",
            ),
        ),
    ]
