# Generated by Django 5.1.1 on 2024-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="F", max_length=1
            ),
            preserve_default=False,
        ),
    ]
