# Generated by Django 5.1.1 on 2024-10-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_animal_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalHeatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
