# Generated by Django 5.1.1 on 2024-10-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animalheatevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalServedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "serve_type",
                    models.CharField(
                        choices=[
                            ("AI", "Artificial Insemination"),
                            ("Bull", "Natural Bull"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="animals.animal",
                    ),
                ),
                (
                    "genetics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="animals.animalbreed",
                    ),
                ),
            ],
        ),
    ]
