# Generated by Django 5.1.1 on 2024-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_animalservedevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaltype",
            name="gestation_period_days",
            field=models.IntegerField(default=283),
            preserve_default=False,
        ),
    ]
