# Generated by Django 5.1.1 on 2024-10-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_animaltype_gestation_period_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="date_of_birth_comment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
