# Generated by Django 5.1.1 on 2024-10-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_animal_date_of_birth_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="date_of_birth_comment",
        ),
        migrations.AddField(
            model_name="animal",
            name="date_of_birth_approximate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
