# Generated by Django 5.1.1 on 2024-10-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AnimalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_id", models.CharField(blank=True, max_length=100, null=True)),
                ("nick_name", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateTimeField()),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="father_animal",
                        to="app.animal",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mother_animal",
                        to="app.animal",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.animalbreed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_purchase", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buyer", models.CharField(max_length=100)),
                ("buyer_contact", models.CharField(max_length=100)),
                ("buyer_address", models.TextField()),
                ("seller", models.CharField(max_length=100)),
                ("seller_contact", models.CharField(max_length=100)),
                ("seller_address", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sale", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buyer", models.CharField(max_length=100)),
                ("buyer_contact", models.CharField(max_length=100)),
                ("buyer_address", models.TextField()),
                ("seller", models.CharField(max_length=100)),
                ("seller_contact", models.CharField(max_length=100)),
                ("seller_address", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.animal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animalbreed",
            name="animal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.animaltype",
            ),
        ),
    ]
